services:
  frontend:
    container_name: infiswap_frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${FRONT_PORT:-3000}:3000"
    working_dir: /app
    volumes:
      - .:/app
      - front_node_modules:/app/node_modules
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
    restart: unless-stopped

volumes:
  front_node_modules:
