services:
  frontend-staging:
    container_name: infiswap_frontend_staging
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - infiswap_network

networks:
  infiswap_network:
    driver: bridge
