services:
  frontend:
    container_name: infiswap_frontend
    image: docker.io/${DOCKERHUB_USERNAME}/front-app:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - infiswap_network

networks:
  infiswap_network:
    driver: bridge
