export const SETTINGS_TOOLTIPS = {
    institutionName: 'settings.tooltips.institutionName',
    lastname: 'settings.tooltips.lastname',
    firstname: 'settings.tooltips.firstname',
    dateOfBirth: 'settings.tooltips.dateOfBirth',
    email: 'settings.tooltips.email',
    identifierNumber: 'settings.tooltips.identifierNumber',
    phoneNumber: 'settings.tooltips.phoneNumber',
    gender: 'settings.tooltips.gender',
    professionalCategory: 'settings.tooltips.professionalCategory',
    educationLevel: 'settings.tooltips.educationLevel',
    street: 'settings.tooltips.street',
    city: 'settings.tooltips.city',
    country: 'settings.tooltips.country',
    workingAt: 'settings.tooltips.workingAt',
    zipCode: 'settings.tooltips.zipCode',
    additionalInfo: 'settings.tooltips.additionalInfo',
    password: 'settings.tooltips.password',
    twoFactor: 'settings.tooltips.twoFactor',
    zipCodesPreference: 'settings.tooltips.zipCodesPreference',
    citiesPreference: 'settings.tooltips.citiesPreference',
    language: 'settings.tooltips.language',
    newReplacement: 'settings.tooltips.newReplacement',
    replacementAccepted: 'settings.tooltips.replacementAccepted',
    digestWeekly: 'settings.tooltips.digestWeekly',
    marketingEmails: 'settings.tooltips.marketingEmails',
    urgentOnly: 'settings.tooltips.urgentOnly',
    smsUrgent: 'settings.tooltips.smsUrgent',
} as const;

export type SettingsTooltipKey = keyof typeof SETTINGS_TOOLTIPS;
