export const SETTINGS_TOOLTIPS = {
    institutionName: 'Nom officiel de votre établissement tel qu\'il apparaît sur InfiSwap.',
    lastname: 'Votre nom de famille, visible par les collègues avec lesquels vous interagissez.',
    firstname: 'Votre prénom, affiché sur votre profil et vos candidatures.',
    dateOfBirth: 'Date de naissance enregistrée sur votre profil professionnel.',
    email: 'Adresse utilisée pour la connexion, les notifications et l\'authentification à deux facteurs.',
    identifierNumber: 'Numéro d\'identification professionnel (N° INAMI ou équivalent selon votre pays).',
    phoneNumber: 'Numéro de contact. Requis pour les SMS urgents si cette option est activée.',
    gender: 'Information de profil utilisée pour l\'affichage de votre compte.',
    professionalCategory: 'Salarié(e) ou indépendant(e).',
    educationLevel: 'Niveau d\'études infirmier en Belgique : Gradué (A1) ou Brevet (A2).',
    street: 'Adresse postale — rue et numéro.',
    city: 'Ville de votre domicile ou cabinet.',
    country: 'Pays de résidence enregistré sur votre profil.',
    workingAt: 'Pays ou zone où vous exercez habituellement.',
    zipCode: 'Code postal de votre adresse. Utilisé comme zone par défaut si vous n\'avez pas configuré de préférences.',
    additionalInfo: 'Informations complémentaires d\'adresse (bâtiment, étage, boîte…).',
    password: 'Modifiez le mot de passe de connexion à votre compte.',
    twoFactor: 'Un code à 6 chiffres envoyé par e-mail lors de l\'activation ou de certaines connexions.',
    zipCodesPreference: 'Codes postaux cibles pour les annonces et le résumé hebdomadaire. La zone correspond aux deux premiers chiffres du code.',
    citiesPreference: 'Villes associées à vos recherches de remplacement, en complément des codes postaux.',
    language: 'Langue de l\'interface. D\'autres langues seront proposées prochainement.',
    newReplacement: 'Notification immédiate (cloche et e-mail) lorsqu\'une nouvelle annonce correspond à votre zone.',
    replacementAccepted: 'Notification lorsqu\'un collègue accepte votre candidature ou confirme un remplacement avec vous.',
    digestWeekly: 'Chaque semaine, un e-mail récapitule les nouvelles annonces publiées dans votre zone (codes postaux des Préférences). Opt-in : désactivé par défaut.',
    marketingEmails: 'Emails promotionnels InfiSwap et présentation de partenaires (NursTech, NursAssur). Les leads nominatifs ne sont transmis au partenaire qu\'avec un consentement distinct sur le formulaire de contact. Opt-in : désactivé par défaut.',
    urgentOnly: 'Limite les notifications aux seules annonces marquées urgentes. Les autres nouveautés de zone sont ignorées.',
    smsUrgent: 'SMS pour les remplacements urgents dans votre zone. Nécessite un numéro de mobile valide et l\'activation côté plateforme.',
} as const;

export type SettingsTooltipKey = keyof typeof SETTINGS_TOOLTIPS;
