// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaD9d78EERz_NjsHAPuDTMarWFnmeedGQ',
    appId: '1:249150725582:web:d61a5f10f8a726b4f49f9f',
    messagingSenderId: '249150725582',
    projectId: 'infiswap-1c10f',
    authDomain: 'infiswap-1c10f.firebaseapp.com',
    storageBucket: 'infiswap-1c10f.firebasestorage.app',
    measurementId: 'G-7Q0CEEBDY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPaycD7lolAao79eEDNBj6J7D3U34WNJ8',
    appId: '1:249150725582:android:b2aaea1b1b0e3894f49f9f',
    messagingSenderId: '249150725582',
    projectId: 'infiswap-1c10f',
    storageBucket: 'infiswap-1c10f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Rk1fS5DyBgiQZSX8c1trTtvNHmAPEvw',
    appId: '1:249150725582:ios:34c2005ca7af19cef49f9f',
    messagingSenderId: '249150725582',
    projectId: 'infiswap-1c10f',
    storageBucket: 'infiswap-1c10f.firebasestorage.app',
    iosBundleId: 'com.infiswap.mobile',
  );
}
